# 1 Import the numpy package 

In [3]:
import numpy as np


# 2. Create a null vector of size 20

In [6]:
null=np.zeros(20)
null

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [7]:
null.dtype

dtype('float64')

In [5]:
#convert float into integer datatype
null=np.zeros(10,"int64")
null

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# 3. Create a vector with values ranging from 10 to 49

In [12]:
val=np.array(range(10,49))
val

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [13]:
#simple array make by arange function
val=np.arange(10,49)
val

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

# 4. Find the shape of previous array in question 3

In [15]:
val.shape 

(39,)

# 5. Print the type and datatype of the previous array in question 3

In [16]:
val.dtype

dtype('int64')

In [21]:
type(val)

numpy.ndarray

# 6. Print the numpy version and the configuration


In [22]:
np.__version__

'1.18.5'

In [28]:
np.__config__

<module 'numpy.__config__' from '/opt/anaconda3/lib/python3.8/site-packages/numpy/__config__.py'>

In [30]:
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/include']


# 7. Print the dimension of the array in question 3

In [47]:
 #by there  no. of ending prhantics we can easily see out this is 1-D ARRAY:
val.ndim

1

# 8. Create a boolean array with all the True values

In [41]:
array=np.array(range(10,30),dtype=bool)
array

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

# 9. Create a two dimensional array

In [44]:
array1=np.arange(30).reshape(15,2)
array1 

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29]])

In [46]:
 #by there no. of ending prhantics we can easily see out this is 2-D ARRAY:
array1.ndim

2

# 10. Create a three dimensional array

In [50]:
array2=np.arange(40).reshape(2,10,2)
array2 

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29],
        [30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]]])

In [51]:
 #by there no. of ending prhantics we can easily see out this is 3-D ARRAY:
array2.ndim

3

# 11. Reverse a vector (first element becomes last)

In [66]:
val[::-1]

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

# 12. Create a null vector of size 10 but the fifth value which is 1


In [76]:
null=np.zeros(10,"int64")
null[5]=1
null

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

# 13. Create a 3x3 identity matrix


In [78]:
np.arange(27).reshape(3,3,3)


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

# 14. arr = np.array([1, 2, 3, 4, 5])

 # Convert the data type of the given array from int to float

In [79]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [80]:
arr.dtype

dtype('int64')

In [81]:
#convert int into float
arr=np.array([1,2,3,4,5],dtype=float)
arr

array([1., 2., 3., 4., 5.])

In [82]:
#convert int into float
arr=np.array([1,2,3,4,5],"float")
arr

array([1., 2., 3., 4., 5.])

# 15. 
# arr1 = np.array([[1., 2., 3.], [4., 5., 6.]]) 
# arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

 # Multiply arr1 with arr2

In [85]:
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
array3=arr1*arr2
array3

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

# 16.
# arr1 = np.array([[1., 2., 3.], [4., 5., 6.]]) 
# arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
# Make an array by comparing both the arrays provided above


In [93]:
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr3=arr1=arr2
arr3

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

# 17. Extract all odd numbers from arr with values(0-9)

In [113]:
val=np.arange(10)
val[val%2==1]

array([1, 3, 5, 7, 9])

# 18. Replace all odd numbers to -1 from previous array


In [121]:
val=np.arange(10)                      #confuse
val[val%2==1]=-1
val

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [117]:
val=np.arange(10)
val[val%2==1][::-1]

array([9, 7, 5, 3, 1])

# 19. 
# arr = np.arange(10)

 # Replace the values of indexes 5,6,7 and 8 to 12

In [123]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [147]:
# replace 5,6,7 and 8 to 12
arr[5]=12
arr[6]=12
arr[7]=12
arr[8]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

# 20. Create a 2d array with 1 on the border and 0 inside

In [214]:
array=np.arange(20).reshape(4,5)
array[0:4]=0
array

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [215]:
array[:,0]=1
array[:,4]=1
array

array([[1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1]])

In [216]:
array[0,:]=1
array

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1]])

In [218]:
array[3,:]=1
array

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

# 21. 
 # arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
 # Replace the value 5 to 12


In [236]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [237]:
arr2d[1,1]=12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

# 22.
# arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
# Convert all the values of 1st array to 64


In [252]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [249]:
arr3d.ndim

3

In [253]:
arr3d[0,0]=64
arr3d

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

# # 23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it


In [260]:
array=np.arange(10).reshape(2,5)
array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [261]:
arr=array[:1]
arr

array([[0, 1, 2, 3, 4]])

In [262]:
arr.flatten() # make 1 _D array  by using flatten we can use reval but it can change orginal value

array([0, 1, 2, 3, 4])

# 24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it


In [278]:
array=np.arange(10).reshape(2,5)
array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [280]:
arr1=array[1]
arr1 #one dimension no need to flatten

array([5, 6, 7, 8, 9])

# 25 :
# Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows


In [295]:
array=np.arange(20).reshape(4,5)
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [298]:
array[0:2,0:3]

array([[0, 1, 2],
       [5, 6, 7]])

# 26:
# Create a 10x10 array with random values and find the minimum and maximum values


In [306]:
array=np.arange(100).reshape(10,10)
array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [307]:
array.max()

99

In [308]:
array.min()

0

# 27.     
# a = np.array([1,2,3,2,3,4,3,4,5,6]) 
# b = np.array([7,2,10,2,7,4,9,4,9,8])
 # Find the common items between a and b



In [322]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])


In [323]:
np.intersect1d(a,b)

array([2, 4])

# 28 
# 28. a = np.array([1,2,3,2,3,4,3,4,5,6])
# b = np.array([7,2,10,2,7,4,9,4,9,8])

---
# Find the positions where elements of a and b match


In [327]:
np.where(a==b)

(array([1, 3, 5, 7]),)

# 29
# names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)
# Find all the values from array data where the values from array names are not equal to Will


In [338]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data[names!="will"]
#genrate random value

array([[-1.60656106,  0.70012384, -0.65102736,  0.21863561],
       [ 0.61481733, -0.55963173, -0.74348576,  1.06384159],
       [-2.05393162, -0.05319488,  1.0194407 , -0.91310549],
       [ 0.62856117, -1.58096821, -0.27805616,  0.29051931],
       [-0.00900286,  0.05177307,  0.15034151, -1.3805115 ],
       [ 0.58497835, -0.93654104,  1.03170935,  0.82962623],
       [-0.28953243,  0.75335732, -0.85336828,  1.55730271]])

# # 30
# names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)
 # Find all the values from array data where the values from array names are not equal to Will AND JOE


In [462]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
not_equal=(names!='Will')&(names!='Joe')
data[not_equal]
#genrate random value

array([[-1.99148531, -0.51710174, -2.0417627 ,  1.13490072],
       [ 1.74341304, -0.73400101,  0.90704426, -1.24552487]])

# 31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.


In [346]:
array=np.arange(15).reshape(5,3)
array

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [349]:
array.astype(np.float)

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.]])


# 32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.


In [358]:
array=np.arange(16).reshape(2,2,4)
array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [359]:
array.astype(np.float)

array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.]],

       [[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]]])

# 33. Swap axes of the array you created in Question 32


In [367]:
array=np.arange(16).reshape(2,2,4)
array.astype(np.float)
np.swapaxes(array,0,1) #1 AXIS

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [368]:
array=np.arange(16).reshape(2,2,4)
array.astype(np.float)
np.swapaxes(array,0,2) # 2AXIS 

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

# 34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0


In [377]:
array=np.arange(10)

In [378]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [383]:
array/18

array([0.        , 0.05555556, 0.11111111, 0.16666667, 0.22222222,
       0.27777778, 0.33333333, 0.38888889, 0.44444444, 0.5       ])

In [386]:
array[:]=0

In [388]:
array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# 35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays


In [408]:
a=np.random.uniform(0,12,12)
b=np.random.uniform(0,12,12)
max(a) , max(b)

(11.075990750545632, 11.329348878037703)

# 36
# names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

# Find the unique names and sort them out!

In [413]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

# 37 . 
# a = np.array([1,2,3,4,5])
 # b = np.array([5,6,7,8,9])

---
 # From array a remove all items present in array b


In [414]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

# 38 
# Following is the input NumPy array delete column two and insert following new column in its place.

# sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])

# newColumn = numpy.array([[10,10,10]])

In [439]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
sampleArray

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [440]:
np.delete(sampleArray, 1 , axis=1)

array([[34, 73],
       [82, 12],
       [53, 66]])

In [443]:
arrayt=np.delete(sampleArray, 1 , axis=1)
array
newColumn = np.array([[10,10,10]])
np.insert(array, 1, newColumn , axis=1)

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

In [445]:
arrayt=np.delete(sampleArray, 1 , axis=1)
array
newColumn = np.array([[10,10,10]])
np.insert(array, 2, newColumn , axis=1)

array([[34, 73, 10],
       [82, 12, 10],
       [53, 66, 10]])

# 39
# x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])

# Find the dot product of the above two matrix

In [448]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

# 40.
# Generate a matrix of 20 random values and find its cumulative sum

In [450]:
matrics=np.arange(20)
matrics

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [456]:
rand=np.random.uniform(matrics)
rand

array([ 0.29202052,  1.        ,  1.52625254,  1.04840467,  3.98593016,
        3.91908359,  4.09049596,  5.56831889,  6.63539187,  7.79379495,
        8.59803836,  9.26290283,  4.98517814,  3.79746494,  2.1245857 ,
       11.91583567,  1.68190646,  5.83957185,  3.47726305,  6.08521286])

In [1]:
np.sum(rand)



NameError: name 'np' is not defined